services:
  - type: web
    name: polylance-fv-1
    env: node
    region: singapore
    plan: free
    rootDir: polylance-chat-service
    buildCommand: npm install --legacy-peer-deps && npx prisma db push && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BACKUP_DATABASE_URL
        sync: false
      - key: RPC_URL
        value: https://polygon-bor-rpc.publicnode.com
      - key: JOB_FACTORY_ADDRESS
        value: 0xbE74923BBfd72d400a681915dBcf6e6Adc72C317
      - key: ALLOWED_ORIGINS
        value: https://polylance-fv-1.onrender.com,https://polylance.github.io,https://polylance.codes,http://localhost:5173
      - key: NODE_ENV
        value: production

      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        value: 10000

