services:
  - type: web
    name: polylance-fv-1
    env: node
    region: singapore
    plan: free
    rootDir: polylance-chat-service
    buildCommand: npm install --legacy-peer-deps && npx prisma db push && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BACKUP_DATABASE_URL
        sync: false
      - key: RPC_URL
        value: https://rpc-amoy.polygon.technology
      - key: JOB_FACTORY_ADDRESS
        value: 0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
      - key: ALLOWED_ORIGINS
        value: https://polylance-fv-1.onrender.com,https://polylance.github.io,https://polylance.codes,http://localhost:5173
      - key: NODE_ENV
        value: production

      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        value: 10000

